### PR TITLE
Add crude support for other mods that add landfill

### PR DESCRIPTION
**Pull request by Jelmergu**
like landfill painting

### CODE REVIEW

**Comment by MarcGamesons** [comment]
Just to make sure I fully understand what this does... It adds support for items that have landfill in their name that are added by other mods, right?

**Comment by Jelmergu** [comment]
Yes. I used this modification of your mod heavily in my SeaBlock save, with landfill painting.

**Review by MarcGamesons — APPROVED** [review]
Thanks for committing "crude" support for other mods that add landfills. I will add this to the main branch and increase the mods version to 1.6.0 so that people will get the new update.

**Comment by MarcGamesons** [comment]
Adding "crude" mod support for other mods that add landfills. Thanks to @Jelmergu for contributing these changes.

**Comment by MarcGamesons** [comment]
Adding "crude" mod support for other mods that add landfills. Thanks to @Jelmergu for contributing these changes.

**Comment by MarcGamesons** [comment]
Sorry I am still learning how GitHub works and made some unwanted comments and accidentally locked the conversation.

**Pull request merged**
